<?php
	include('php/FichierCSV.php');
	
	// Création d'une instance de la classe FichierExcel
	$csv = new FichierCSV();
	
	// Initialisation des différentes colonnes
	$csv->Insertion("Nom;\"Actions\";\"Modalités\";\"Temps(min)\"");

	// Insertion des données
	foreach($tab_results as $action => $code){
		foreach($code['subcode'] as $subcode => $value){
					$csv->Insertion('"'.$nomCal.'";"'.$action.'";"'.$subcode.'";'.($value/60).'');
		}
	}
	
	// Restitution du fichier
	$csv->output("".$nomCal."");
	exit;
?>