	
</div>		
		
<script src="http://code.jquery.com/jquery-latest.js"></script>		
<script type="text/javascript" src="js/bootstrap.js"></script>
<script type="text/javascript" src="js/bootstrap-datepicker.js"></script>


<script type="text/javascript">
	$('#simpleError').click(function () {
		if($('#simpleError').is(':checked')){
			$('.errorLvl0').css('display','list-item');
		} else {
			$('.errorLvl0').css('display','none');
		}
	});

	$('#seriousError').click(function () {
		if($('#seriousError').is(':checked')){
			$('.errorLvl1').css('display','list-item');
		} else {
			$('.errorLvl1').css('display','none');
		}
	});

	$('#warningError').click(function () {
		if($('#warningError').is(':checked')){
			$('.errorLvl2').css('display','list-item');
		} else {
			$('.errorLvl2').css('display','none');
		}
	});
</script>


			
		<script>
			$('.datepicker').datepicker();
		</script>
	</body>
</html>

