<!doctype html>
<html class="no-js" lang="fr">
    <head>

        <meta charset="utf-8" />
        <title>CDG : Analyseur de calendrier</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/bootstrap-responsive.min.css">
		<link rel="stylesheet" href="css/datepicker.css">
        <link rel="stylesheet" href="css/style.css">

    </head>

    <body>
		<div class="container-fluid">

<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#Actions" data-toggle="tab">Liste des Actions</a></li>
  <li><a href="#Modalites" data-toggle="tab">Liste des Modalites</a></li>
  <li><a href="#Calcul" data-toggle="tab">Calcul</a></li>
</ul>



<div id="myTabContent" class="tab-content">
<div class="tab-pane in active" id="Actions">
	<form action="index.php" method="post" class="form-inline">
		<button id="exportTableauAction" class="btn btn-info" type="submit" name="action" value="tableauAction">
			<i class="icon-download-alt icon-white"></i> Exporter
		</button>
		<label class="checkbox">
			<input type="checkbox" id="showArchived" name="showArchived" value="1">Voir les actions archivées.</input>
		</label>
	</form>
	
	<table class="table table-striped table-bordered table-condensed">
		<thead>
			<tr>
				<th>Code</th>
				<th>Intitulé</th>
				<th>Description</th>
				<th>Référent</th>
			</tr>
		</thead>
		<tbody>
<?php
	// Permet l'affichage du tableau des actions du cdg
	foreach ($GLOBALS["actions"] as $action => $value) {
		if ($value['Visible'] == 1) 
			print "\t\t\t<tr class=\"actual\">";
		else
			print "\t\t\t<tr class=\"archived\">";
		print "<td>".$action."</td>";
		print "<td>".$value['Intitulé']."</td>";
		print "<td>".$value['Description']."</td>";
		print "<td>".$value['Referent']."</td>";

		print "</tr>\n";
		
	}
?>
		</tbody>
	</table>
</div>

<div class="tab-pane fade" id="Modalites">	
	<form action="index.php" method="post">
	<button id="exportTableauModalite" class="btn btn-info" type="submit" name="action" value="tableauModalite">
		<i class="icon-download-alt icon-white"></i> Exporter
	</button>
</form>
	<table class="table table-striped table-bordered table-condensed">
		<thead>
			<tr>
				<th>Code</th>
				<th>Intitulé</th>
				<th>Description</th>
			</tr>
		</thead>

		<tbody>

			<?php
			// Permet l'affichage du tableau des modalites du cdg
			foreach ($GLOBALS["modalites"] as $modalite => $value) {
				print "\t\t\t<tr>";
				print '<td>' . $modalite . '</td>';
				foreach ($value as $key => $values) {
					print '<td>' . $values . '</td>';
				}
				print "</tr>\n";
			}
			?>

		</tbody>
	</table>
</div>


<div class="tab-pane fade" id="Calcul">
		<form method="post" action="index.php" class="form-horizontal span5">
			<div class="control-group">
				<label class="control-label" for="ics">Utilisateur(s) : </label>
				<div class="controls">

					<?php
					// Récupération et affichage du nom des calendriers
					$tab_cal_path = $this->model->getCalList();

					print('<select name="ics[]" size=10 class="span3" multiple="multiple">');

					// Récupération des calendriers
					foreach ($tab_cal_path as $key => $value) {

						$nomCal = basename($value);
						$nomCal = explode(".", $nomCal)[0];

						print('<option id="' . $key . '" name="ics" value="' . $value . '">' . $nomCal . '</option>');
					}
					print("</select>");
					?>
				</div>

			</div>

			<!-- Formulaire -->
			<div class="control-group">

				<label class="control-label" for="date_debut">Date de début : </label>
				<div class="controls">
					<div class="input-append date datepicker" id="dp3" data-date="<?php print(date("d-m-Y")); ?>" data-date-format="dd-mm-yyyy">
						<input id="date_debut" class="span2" value="<?php print(date("d-m-Y")); ?>" type="text" name="startDate" required="required" readonly/>
						<span class="add-on"><i class="icon-calendar"></i></span>

					</div>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="date_fin">Date de fin :</label>
				<div class="controls">

					<div class="input-append date datepicker" id="dp2" data-date="<?php print(date("d-m-Y")); ?>" data-date-format="dd-mm-yyyy">
						<input id="date_fin" class="span2" value="<?php print(date("d-m-Y")); ?>" type="text" name="endDate" required="required" readonly/>
						<span class="add-on"><i class="icon-calendar"></i></span>
					</div>
				</div>
			</div>

			<div class="control-group">
				<div class="control-group">
					<label class="control-label" for="ics">Export : </label>
					<div class="controls">
						<select class="span3" name="export">
							<option value="All"   >Total</option>
							<option value="day"   >Par jours</option>
							<option value="week"  >Par semaines</option>
							<option value="month" >Par mois</option>
							<option value="year"  >Par ans</option>
						</select>

					</div>
				</div>
			</div>

			<div class="control-group">
				<div class="controls">
					<button id="showresults" class="btn btn-primary" type="submit" name="action" value="Show">
						<i class="icon-eye-open icon-white"></i> Afficher</button> 
					<button id="export" class="btn btn-info control-button" type="submit" name="action" value="Export">
						<i class="icon-download-alt icon-white"></i> Exporter
					</button>
				</div>
			</div>

			

		</form>	
</div>
</div>

	
</div>		
			
<script type="text/javascript" src="js/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/bootstrap-datepicker.js"></script>


<script type="text/javascript">
	$('#simpleError').click(function () {
		if($('#simpleError').is(':checked')){
			$('.errorLvl0').css('display','list-item');
		} else {
			$('.errorLvl0').css('display','none');
		}
	});

	$('#seriousError').click(function () {
		if($('#seriousError').is(':checked')){
			$('.errorLvl1').css('display','list-item');
		} else {
			$('.errorLvl1').css('display','none');
		}
	});

	$('#warningError').click(function () {
		if($('#warningError').is(':checked')){
			$('.errorLvl2').css('display','list-item');
		} else {
			$('.errorLvl2').css('display','none');
		}
	});

	$('#showArchived').on("click", function() {
		if($('#showArchived').is(':checked')){
			$('tr.archived').css('display', 'table-row');
		} else {
			$('tr.archived').css('display', 'none');
		}
	});
</script>
			
<script>
	$('.datepicker').datepicker();
</script>

<script>
	
</script>

</body>
</html>
