<!doctype html>
<html class="no-js" lang="fr">
    <head>

        <meta charset="utf-8" />
        <title>CDG : Analyseur de calendrier</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="css/bootstrap.css">
		<link rel="stylesheet" href="css/bootstrap-responsive.css">
		<link rel="stylesheet" href="css/datepicker.css">
        <link rel="stylesheet" href="css/style.css">

    </head>

    <body>
		<div class="container-fluid">